sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - yarn prune
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
